name: CD

on:
  # enables manual triggers
  workflow_dispatch:

jobs:
  deploy-dev:
    name: Deploy to development
    runs-on: ubuntu-latest
    environment: development
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    steps:
      - name: Deploy Artifact
        run: echo "Deployed to development environment"

  deploy-test:
    name: Deploy to test
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment: test
    steps:
      - name: Deploy Artifact
        run: |
          echo "Deployed to test environment"
          # curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.APT }}" -H "X-GitHub-Api-Version: 2022-11-28" "https://api.github.com/repos/n00b88/${{ secrets.REPONAME }}/dispatches" -d "{\"event_type\": \"trigger-workflow\", \"client_payload\": {\"service\": \"$service\", \"version\": \"$version\", \"unit\": false, \"integration\": true}}"
          curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.PAT }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/n00b88/${{ secrets.REPONAME }/dispatches -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"trigger\": \"${{github.run_id}}-${{github.workflow_ref}}-${{github.run_id}}\", \"version\": \"$version\", \"unit\": false, \"integration\": true}}"
